name: MCNR-Utils
version: '8'
main: xyz.mcnr.utils.Main
api-version: '1.21'
commands:
  help:
    usage: '/help'
  rst:
    usage: '/rst'
  joins:
    usage: '/joins <player>'
  w:
    usage: '/<command> <player> <message>'
    aliases: [msg, pm, tell]
  r:
    usage: '/<command> <message>'
  last:
    usage: '/<command> <message>'
    aliases: [l]
  ignore:
    usage: '/<command> <player>'
    aliases: [i, ign]
  ignorelist:
    usage: '/<command>'
    aliases: [il]
  afk:
    usage: '/<command>'
  report:
    usage: '/<command>'
  anon:
    usage: '/<command> <message>'
  toggleanon:
    usage: '/<command>'
