name: MCNR-Utils
version: '17'
main: xyz.mcnr.utils.Main
api-version: '1.21.4'
commands:
  help:
    usage: '/help'
  rst:
    usage: '/rst'
  joindate:
    usage: '/joindate <player>'
    aliases: [jd]
  w:
    usage: '/<command> <player> <message>'
    aliases: [msg, pm, tell]
  r:
    usage: '/<command> <message>'
  last:
    usage: '/<command> <message>'
    aliases: [l]
  ignore:
    usage: '/<command> <player>'
    aliases: [i, ign]
  ignorelist:
    usage: '/<command>'
    aliases: [il]
  afk:
    usage: '/<command>'
  bugreport:
    usage: '/<command>'
  anon:
    usage: '/<command> <message>'
  toggleanon:
    usage: '/<command>'
    aliases: [ignoreanon]
  togglejd:
    usage: '/<command>'
    aliases: [hidejd]
  read:
    usage: '/<command>'