name: MCNR-Utils
version: '5'
main: xyz.mcnr.utils.Main
api-version: '1.21'
commands:
  help:
    usage: '/help'
  rst:
    usage: '/rst'
  joins:
    usage: '/joins <player>'
  whisper:
    usage: '/<command> <player> <message>'
    aliases: [w, msg, pm]
  reply:
    usage: '/<command> <message>'
    aliases: [r]
  last:
    usage: '/<command> <message>'
    aliases: [l]
  ignore:
    usage: '/<command> <player>'